#Created by BGHDDevelopment(Noodles)
#Discord/Support: https://bghddevelopment.com/discord
#Plugin Link: https://www.spigotmc.org/resources/52072/
#Website: https://bghddevelopment.com
#Wiki: https://wiki.bghddevelopment.com/books/punishmentgui---litebansgui-advancedbangui
#Ideas/Feedback: https://feedback.bghddevelopment.com/
#=======================================================
#Permssion: punishmentgui.update
Update:
  Enabled: true
#Enables if there is a message on-join when the plugin is outdated.
#=======================================================
#Commands & Permissions:
#/punish (playername) - punish.use
#=======================================================
#Main Command Messages:
Prefix: "&8Punish &7>> "
NoMessage: "&cInvalid! Use like /punish (player)!"
NoPermission: "&c(!) You don't have permission to use this command!"
NoPlayer: "Only players can use this command!"
NameLength: "&cThis name is too long! You can only enter 16 characters!"
#=======================================================
InventoryName: "&c&lPunishments"
