name: PunishmentGUI
version: ${project.version}
main: me.noodles.gui.PunishmentGUI
authors: [BGHDDevelopment]
description: A GUI plugin that connects to any punishment plugin.
website: https://bghddevelopment.com
commands:
   punish:
      description: /punish (player).
   punishmentgui:
      description: Information about PunishmentGUI.
   punishmentguireload:
      description: Reloads config file.